### ISSUE TITLE
Suggestion: using yt-navigate-finish instead of setInterval

### ISSUE THREAD

**Issue by cyfung1031** [cvzi/Youtube-Genius-Lyrics-userscript#10]
The script is currently using `window.setInterval(main, 2000)`
inside `main()`, it calls querySelector and textContent which are expensive.

Refer to the code, it just wants to check when the song is changed.
I recommend using yt-navigate-finish / yt-page-data-fetched / yt-page-data-updated to avoid the setInterval checking.
`yt-navigate-finish` should be the most easy one. This event triggers after the song changed and UI ready.

```js
main(); // first call
document.addEventListener('yt-navigate-finish', main, false); // trigger when song is changed
```

**Comment by cyfung1031** [comment]
> Sure, you can make a pull request if you like

pull request https://github.com/cvzi/Youtube-Genius-Lyrics-userscript/pull/12

**Comment by cyfung1031** [comment]
However, looks like it is still not working.
it seems that `main()` is called by `geniusLyrics({...})` with 2s interval.

**Comment by cvzi** [comment]
It's fine for me, if you can make it work. I can adapt the other scripts afterwards.

**Comment by cyfung1031** [comment]
Closed. The setInterval is primarily eliminated by using youtube event triggering, but the relevant coding to be optimized.
