### ISSUE TITLE
Genius Lyrics's iframe creates history records

### ISSUE THREAD

**Issue by cyfung1031** [cvzi/Youtube-Genius-Lyrics-userscript#11]
I understand that this script is using iframe to youtube domain robot txt to get the lyrcis.
I believe the linking inside iframe can be done by "`location.replace(...)`" instead of "`location = XXX`" or "`location.href = XXX`"

By using <a href="https://developer.mozilla.org/en-US/docs/Web/API/Location/replace">location.replace</a>, the history record would not be affected (to the top frame).

Please consider such feature.
Since youtube can navigate among songs, the history modification would make trouble to this YouTube feature.

**Comment by cvzi** [comment]
Can you check if that helps:
https://github.com/cvzi/genius-lyrics-userscript/pull/10

**Comment by cyfung1031** [comment]
> Can you check if that helps: [cvzi/genius-lyrics-userscript#10](https://github.com/cvzi/genius-lyrics-userscript/pull/10)

I have tried this. It works ~ Please merge the pull request and update the master file.
