### ISSUE TITLE
Styling and Userscript Interfacing

### ISSUE THREAD

**Issue by cyfung1031** [cvzi/Youtube-Genius-Lyrics-userscript#13]
Would you mind to provide some interfacing so that the genius object and the useful functions can be exported to the outside and called by other userscripts?

Right now I am doing some interfacing of your script with my script.
https://greasyfork.org/en/scripts/428651-tabview-youtube

---------

Besides, there are three things I would like to do.

If you would like to include into your script, I am fine to share it.
If not, I would just add to my script to make these features.

### **Point 1) modify the css styling of the floating elements to adopt the darker dark theme** 

> I know this youtube genius lyrics userscript is quite old and now YouTube has decided to make dark mode as default.
> For me I think the old css styling used is a bit ugly.

### **Point 2) modify the css styling within the iframe**

> I just use the default theme (genius theme), looks like the texts are somehow broken especially the header and footer.
> I have already figured out the required css. 
> For other two themes, seems not maintained and already broken?
> Or add my styling as a separate theme?
> For this purpose, I hope there is some exported functions that I can call to set the theme or add custom theme by css in order to incorporate my userscript design.

### **Point 3) a more accurate way to get the song title and author**

> I see there is some text processing for the video title to get the actual song name and author.
> Base on the latest design, I have figured out another way to do it. But I don't know how to feed the title to your script correctly.
> 
> Actually it is quite easy. 
> Example Video:
> https://www.youtube.com/watch?v=F6SDc5uMEgs&list=PL4fGSI1pDJn5FhDrWnRp2NLzJCoPliNgT&index=11
> ![Screen Shot 2022-12-12 at 20 17 25](https://user-images.githubusercontent.com/44498510/207032807-99d02376-1a09-44d9-adb0-64cd7dafd32e.png)
> 
> In the latest YouTube design, the music information is captured with song title and author. just check whether these two information both appear in the video title. If both appear, then genius can highly able to get the correct and unique result.
> I think this can be the first priority on top of the current method.
> 
> I already have the js code to get the song title and song author.

Regarding these three points, please let me know what do you want.

---------

Point 1.
(Still some fine tuning for light theme colors)

<img src="https://user-images.githubusercontent.com/44498510/207034184-1b5a7059-1090-44c8-b1fd-1c8fa550a98b.png" width="500" /><img src="https://user-images.githubusercontent.com/44498510/207034178-d71ab9d6-9b05-4bc5-a2ea-0edb86e5fcd9.png" width="300" />
<img src="https://user-images.githubusercontent.com/44498510/207034177-dd14d5f7-f411-4fab-a706-42d1f1b564c1.png" width="400" />
 

Point 2.
(Still some fine tuning for light theme colors)

<img src="https://user-images.githubusercontent.com/44498510/207034187-d7707ee5-4eb3-4007-9cff-8e45c38291b0.png" width="300" /><img src="https://user-images.githubusercontent.com/44498510/207034181-9b3705ee-8642-4a36-a6a7-b936ef47d048.png" width="300" />

**Comment by cyfung1031** [comment]
As I don't know how to properly feed the correct video title, my current implementation can be just 

addLyrics -> the searchbox appear -> input the correct title -> simulate the enter in search box

I hope there is a proper and direct way to feed the correct title.

**Comment by cvzi** [comment]
In general, I am ok, if you want to change the script or the "library" [genius-lyrics-userscript](https://github.com/cvzi/). These three points are good ideas. You can change the existing "Genius" theme.

As long as it works with the other scripts or it is not too much work for me to adapt the other scripts, I am fine with changes. My only other requirement would be: it should work with both Firefox and Chrome with Tampermonkey.

I don't use Youtube anymore for music, I use Spotify. I just occasionally watch a music video. So I don't really have the motivation to improve this script for Youtube myself.
Also I don't care about performance at all 😂

**Comment by cyfung1031** [comment]
> In general, I am ok, if you want to change the script or the "library" [genius-lyrics-userscript](https://github.com/cvzi/). These three points are good ideas. You can change the existing "Genius" theme.
> 
> As long as it works with the other scripts or it is not too much work for me to adapt the other scripts, I am fine with changes. My only other requirement would be: it should work with both Firefox and Chrome with Tampermonkey.
> 
> I don't use Youtube anymore for music, I use Spotify. I just occasionally watch a music video. So I don't really have the motivation to improve this script for Youtube myself. Also I don't care about performance at all 😂

Great. Understand your points.
I only use YouTube to watch music videos and this script was told by some users who are using my userscript.
For YouTube it is complicated web app design allowing users to back-and-forth video playing and browsing.
Therefore the script must be capable to handle the unexpected issues such as the loading is cancelled due to page change or the iframe is no longer valid on page.
I care about the resource usages as the memory leakage could happen if the script running for long time in the Single Page Web App.

As of the following pull requests https://github.com/cvzi/Youtube-Genius-Lyrics-userscript/pull/25 and https://github.com/cvzi/genius-lyrics-userscript/pull/32 are both completed, I am happy with this script.

getting the correct song title and artist name in YouTube is much difficult than Spotify. I have also implemented some coding for this issue as well.

However, I do not use Spotify much and you might bring some codes from this script to Spotify / YouTube Music plugin if you like. The coding using in this plugin has a better performance and resource handling like using CSS over element style, global event handlers, etc.
For Fuzzy Matching, I think it might not be required in Spotify. Up to you. Now YouTube Genius Lyrics is with a good mechanism to automatically select the best matching lyrics if it can find any lyrics result.

**Comment by cyfung1031** [comment]
Completed for Redesign and Interfacing.
Theme Issue to be resolved.

https://github.com/cvzi/genius-lyrics-userscript/pull/37
