### ISSUE TITLE
Error message "You are unable to access genius.com"

### ISSUE THREAD

**Issue by decembre** [cvzi/Youtube-Genius-Lyrics-userscript#5]
Test the script on:
<a href="https://www.youtube.com/watch?v=ovPwUihaVdE">Jacques Brel - La valse à mille temps</a>
Your script open a popu with this error message in html  (i reduce it):

cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies
id="cf-error-details" class="cf-error-details-wrapper"
class="cf-wrapper cf-header cf-error-overview"
data-translate="block_headline" Sorry, you have been blocked
class="cf-subheadline" data-translate="unable_to_access" You are unable to access  genius.com

data-translate="blocked_why_headline" Why have I been blocked? 
data-translate="blocked_why_detail" This website is using a security service to protect itself from online attacks. 
The action you just performed triggered the security solution. 
There are several actions that could trigger this block including submitting a certain word or phrase, 
a SQL command or malformed data.</p>

data-translate="blocked_resolve_headline" What can I do to resolve this?
data-translate="blocked_resolve_detail" You can email the site owner to let them know you were blocked. 
Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.

The problem is on **Waterfox Classic 2020.12**
Your scritpt is installed with Tampermonkey [seems not working with (old) Greasemonkey 3.17]

But it work fine on Chrome and Firefox Quantum.

**Comment by cvzi** [comment]
Does it only happen with that one song or others as well?

**Comment by decembre** [comment]
Always the same problem, but it seems only a profile specific:
When i open this video in another Waterfox's profile, your script work fine.

So, sorry...

But, i don't understand what in this "wrong" profile give this problem:
I have clear my cookies (and restart my PC).
Disable greasemonkey (so no interaction with other scripts from it).
All videos where they are lyrics on Genius, the popup appeare.
Seems not a login problem.

An addon conflict?
Or too many "tweaks" on this profile:
certainly!


PS.
For all browsers:
Some videos don't find the lyrics and don't show the search form,
where other, with no lyrics too, show this search form when i click on the "G" icon of your script.

This one by example:
<a href="https://www.youtube.com/watch?v=AuxFRUNv_ww">Je suis venu te dire que je m'en vais</a>

For these videos (which don't show the search form after click), no problem of cookies with my "bad" profile" .

I don't think you can solve my problem easily, too specific.
Anyway, thanks for your quick reply and sorry for lost time.
;-)

**Comment by cvzi** [comment]
I have no idea what it could be. I don't know much about this Cloudflare thing. I know it is used to block bots but I don't know how exactly it works.

I updated the script, so that the search form should be shown now.
If the (G) icon is not shown, it should now be possible to open the search form from the Tampermonkey menu entry "Show lyrics"

**Comment by decembre** [comment]
"this Cloudflare thing" is a myster for me too....
Thanks for the update:
i test it later.
