### ISSUE TITLE
Incomplete lyrics when selecting "Clean White" or "Spotify" theme

### ISSUE THREAD

**Issue by i486** [cvzi/Youtube-Genius-Lyrics-userscript#62]
**"Clean white" incomplete lyrics**

![image](https://github.com/cvzi/Youtube-Genius-Lyrics-userscript/assets/625325/4a29de57-fcb4-44ab-949f-885d8cb97441)

**"Genius Default" works but font size is too small.**

![image](https://github.com/cvzi/Youtube-Genius-Lyrics-userscript/assets/625325/54f06ebf-a790-4f02-9ba4-fd68c398e7b4)

Firefox: 115.4.0esr (64-bit)

**Comment by cyfung1031** [comment]
@cvzi  any idea regarding the incomplete lyrics in white / spotify theme ? seem the lyrics is removed in the html code.

**Comment by cyfung1031** [comment]
@i486 

1. Right click the lyrics, click inspect.  in the opened DevTools, type `((s)=>{console.log(s.fontFamily, s.fontSize)})(getComputedStyle(document.querySelector('#lyrics-root')||$0));` in the console and press enter. copy the message and post it here.

2. What is your OS ? Mac? Windows 11?

**Comment by i486** [comment]
> @i486
> 
>     1. Right click the lyrics, click inspect.  in the opened DevTools, type `((s)=>{console.log(s.fontFamily, s.fontSize)})(getComputedStyle(document.querySelector('#lyrics-root')||$0));` in the console and press enter. copy the message and post it here.
> 
>     2. What is your OS ? Mac? Windows 11? Guess it is a font issue with the system.

 Clean White
`"Youtube Sans", Roboto, Arial, sans-serif 16px`

Spotify (also incomplete lyrics)
`CircularSp, CircularSp-Arab, CircularSp-Hebr, CircularSp-Cyrl, CircularSp-Grek, CircularSp-Deva, "HelveticaNeue", Arial, sans-serif 16px`

On Windows 7 x64, an admittedly outdated OS, I'm hoping that the script could be adjusted to resolve this issue. However, I am willing to install any required fonts myself if fixing it through the script is not worthwhile.

**Comment by cyfung1031** [comment]
> > @i486
> > ```
> > 1. Right click the lyrics, click inspect.  in the opened DevTools, type `((s)=>{console.log(s.fontFamily, s.fontSize)})(getComputedStyle(document.querySelector('#lyrics-root')||$0));` in the console and press enter. copy the message and post it here.
> > 
> > 2. What is your OS ? Mac? Windows 11? Guess it is a font issue with the system.
> > ```
> 
> Clean White `"Youtube Sans", Roboto, Arial, sans-serif 16px`
> 
> Spotify (also incomplete lyrics) `CircularSp, CircularSp-Arab, CircularSp-Hebr, CircularSp-Cyrl, CircularSp-Grek, CircularSp-Deva, "HelveticaNeue", Arial, sans-serif 16px`
> 
> On Windows 7 x64, an admittedly outdated OS, I'm hoping that the script could be adjusted to resolve this issue. However, I am willing to install any required fonts myself if fixing it through the script is not worthwhile.

I mean the fonts and size for `Genius(Default)` theme. For YouTube Genius Lyrics, clean white and spotify theme are not recommended.

**Comment by cvzi** [comment]
Should be fixed now.

Problem was that genius.com has now multiple `div.Lyrics__Container` that contain the lyrics if the lyrics are long. Previously it was just one `div`
