### ISSUE TITLE
Letters to small,

### ISSUE THREAD

**Issue by blacknighty15** [cvzi/Youtube-Genius-Lyrics-userscript#63]
unable to change lyrics font size, only way is to zoom browser.

**Comment by cvzi** [comment]
Thanks, I see it as well.

The problem is that  `--egl-font-size: 10px;` is set on the html element in the iframe. Not sure how exactly this value gets set...

Anyway, an option to change the font size in the script settings might be a good idea.

**Comment by cvzi** [comment]
I updated the script. Font size should be normal again.

I'll think about adding an option to customize font size

**Comment by blacknighty15** [comment]
Hi,.

In my case the letter is still small,

[image: image.png]

*Emanuel Herrera*
@j0shua15

*"Desconocer la verdad me hace esclavo de una mentira"*

**Comment by cvzi** [comment]
I added an option in the settings of the script to set a font size
