### ISSUE TITLE
Default theme doesn't show lyrics

### ISSUE THREAD

**Issue by votqanh** [cvzi/Youtube-Genius-Lyrics-userscript#7]
![Screen Shot 2021-06-23 at 1 39 46 PM](https://user-images.githubusercontent.com/84301202/123052129-7ca68400-d428-11eb-841d-2ca7b3c7a606.png)

The default theme doesn't show lyrics for me. I'm on the latest version of Chrome on macOS Big Sur.

**Comment by cvzi** [comment]
Thanks, lyrics don't show up for me either

**Comment by votqanh** [comment]
The other themes work though.

**Comment by cvzi** [comment]
Should work again

**Comment by votqanh** [comment]
Looks good. Thanks!
