### ISSUE TITLE
Lyrics shows too narrow

### ISSUE THREAD

**Issue by AsVHEn** [cvzi/Youtube-Genius-Lyrics-userscript#71]
![Captura de pantalla -2024-12-13 16-58-39](https://github.com/user-attachments/assets/9d56fa4a-3722-4ca6-86c0-d48b913c7358)

As image shows.
I did try it on a private tab with only Violentmonkey with the same result.

Thank you for doing it.

**Comment by cvzi** [comment]
The White and Spotify theme should work again.
The "default" theme probably needs some more work to make it pretty again.
