### ISSUE TITLE
Hi. autoShow is buggy.

### ISSUE THREAD

**Issue by cyfung1031** [cvzi/Youtube-Genius-Lyrics-userscript#9]
Hi. autoShow is buggy.

<a href="https://freeimage.host/i/HnmvvFn"><img src="https://iili.io/HnmvvFn.md.png" alt="HnmvvFn.md.png" border="0"></a>
<a href="https://freeimage.host/i/HnmvOGt"><img src="https://iili.io/HnmvOGt.md.png" alt="HnmvOGt.md.png" border="0"></a>

`video.getClientRects()[0].right` shall change to `video.getBoundingClientRect().right` to avoid the bug.

**Comment by cvzi** [comment]
Thanks!
